{
  "os": "linux",
  "env": "CXX=g++-4.8",
  "dist": "trusty",
  "sudo": "required",
  "group": "stable",
  "addons": {
    "apt": {
      "sources": [
        "ubuntu-toolchain-r-test"
      ],
      "packages": [
        "g++-4.8",
        "openjdk-7-jdk",
        "lib32stdc++6",
        "lib32z1",
        "google-chrome-stable"
      ]
    },
    "chrome": "stable"
  },
  "script": [
    "cordova prepare",
    "npm test",
    "ionic build"
  ],
  "install": [
    "npm install -g gulp bower cordova ionic",
    "npm install",
    "bower update"
  ],
  "node_js": "8.11",
  "language": "node_js",
  "before_script": [
    "wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz",
    "tar -xvf android-sdk_r24.4-linux.tgz",
    "echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools",
    "echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2",
    "echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23",
    "echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support",
    "echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository",
    "echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository",
    "export ANDROID_HOME=$PWD/android-sdk-linux",
    "export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2",
    "sudo chown root /opt/google/chrome/chrome-sandbox",
    "sudo chmod 4755 /opt/google/chrome/chrome-sandbox",
    "export CHROME_BIN=chromium-browser",
    "export DISPLAY=:99.0",
    "sh -e /etc/init.d/xvfb start",
    "sleep 10"
  ]
}
